version: '3.7'

services:

# ----------------------- SLICING SERVER -----------------------
    ytp_playlist_download:
        build:
            context: ./src
        command: uvicorn main:app --reload
        depends_on:
            - traefik
            - db
        container_name: ytb_playlist_download
        hostname: ytb_playlist_download
        image: ytb_playlist_download:0.1
        env_file: .env
        networks:
            - db
            - traefik-inside
        volumes:
            - ./src/app:/usr/src/app
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik-inside"
            - "traefik.http.routers.slice-server.rule=PathPrefix(`/ytp-playlist-download/api/0.0`)"
            - "traefik.http.routers.slice-server.entrypoints=http"
            - "traefik.http.services.slice-server.loadbalancer.server.port=80"

# ----------------------- DATABASE  ---------
    db:
        image: postgres:14.5
        container_name: db
        hostname: db
        env_file: ./db/.env
        networks:
            db:
                aliases:
                    - db
        volumes:
            - db:/var/lib/postgresql/data/

    pgadmin:
        depends_on:
            - traefik
        container_name: pgadmin
        hostname: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.fr
            PGADMIN_DEFAULT_PASSWORD: admin
            SCRIPT_NAME: /pgadmin
        volumes:
            - pgadmin:/root/.pgadmin
        networks:
            - db
            - traefik-inside
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik-inside"
            - "traefik.http.routers.pgadmin.rule=PathPrefix(`/pgadmin`)"
            - "traefik.http.routers.pgadmin.entrypoints=http"
            - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
        restart: unless-stopped

# ----------------------- REVERSE PROXY ---------
    traefik:
        build:
            context: ./traefik
        image: reverse_proxy
        container_name: traefik
        hostname: traefik
        ports:
            - 80:80
            - 443:443
            - 8080:8080
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - traefik-inside
            - traefik-outside

# ----------------------- NETWORK -----------------------
networks:
  traefik-inside:
    name: traefik-inside
  traefik-outside:
    name: traefik-outside
  db:
    name: db

# ----------------------- VOLUMES -----------------------
volumes:
    pgadmin:
    db:
